[project]
name = 'Personalized-Medicine-and-Treatment-Optimization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.health-data-sharing]
path = 'contracts/health-data-sharing.clar'
clarity_version = 2
epoch = 2.5

[contracts.health-marketplace]
path = 'contracts/health-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.personal-health-data]
path = 'contracts/personal-health-data.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
